[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
let g:ctrlp_show_hidden = 1
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll|png)$',
  \ 'link': '',
  \ }
let g:ctrlp_use_caching = 0
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup -g "" --hidden'
'''

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = 'source ~/.vim/userautoload/plugins/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
hook_add = 'source ~/.vim/userautoload/plugins/unite-outline.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.vim/userautoload/plugins/nerdtree.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

#[[plugins]]
#repo = 'Shougo/neocomplete.vim'
#hook_add = 'source ~/.vim/userautoload/plugins/neocomplete.vim'
